version: '3.3'
services:
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
      - /tmp/docker/
  app:
    image: oxyac/php_81:0.2
    #    build:
    #      context: ./php
    #      dockerfile: Dockerfile
    container_name: my-app
    restart: always
    working_dir: /var/www/
    links:
    # - rabbitmq
      - my-db
    #    - cache
      - opentts
    volumes:
      - ./../:/var/www/
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    volumes_from:
      - tmp

  nginx:
    image: nginx:1.19-alpine
    container_name: my-nginx
    restart: always
    ports:
      - "6969:80"
    links:
      - my-db:my-db
      - app
    volumes:
      - ./../:/var/www
      - ./conf/nginx:/etc/nginx/conf.d
  my-db:
    image: mysql:5.7
    restart: "no"
    container_name: my-db
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: 'default'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'og'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./conf/mysql/mysql.conf:/etc/mysql/conf.d/mysql.conf

  cache:
    # image: redis_socket:6.2
    build:
      context: ./conf/redis
      dockerfile: Dockerfile
    restart: always
    container_name: my-redis
    ports:
      - '6379:6379'
    command: redis-server /etc/redis.conf --save 20 1 --loglevel warning
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    volumes_from:
      - tmp

  # rabbitmq:
  #   # build: ./rabbitmq
  #   container_name: my-rabbitmq
  #   image: rabbitmq:scs
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672'

  opentts:
    image: synesthesiam/opentts:all
    container_name: my-opentts
    ports:
      - "5500:5500"
volumes:
  mysql-volume:
  redis.conf:
  cache:
    driver: local
